import { NextResponse } from "next/server";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { meeting_id, drafts } = body;

    if (!meeting_id || !drafts || !Array.isArray(drafts) || drafts.length === 0) {
      return NextResponse.json({ error: "Missing required fields (meeting_id, drafts)" }, { status: 400 });
    }

    const geminiApiKey = process.env.GEMINI_API_KEY;
    if (!geminiApiKey) {
      return NextResponse.json({ error: "GEMINI_API_KEY environment variable is not configured" }, { status: 500 });
    }

    const supabase = await createServerSupabaseClient();

    // 1. Fetch meeting configuration
    const { data: meeting, error: meetingError } = await supabase
      .from("meetings")
      .select("target_language, source_language, meeting_context")
      .eq("id", meeting_id)
      .single();

    if (meetingError || !meeting) {
      return NextResponse.json({ error: "Meeting not found" }, { status: 404 });
    }

    // 2. Fetch glossary
    const { data: glossaryList } = await supabase
      .from("glossary")
      .select("source, target, source_language, target_language")
      .eq("meeting_id", meeting_id);

    // 3. Fetch recent transcripts for history context
    const { data: recentTxs } = await supabase
      .from("transcripts")
      .select("original_text, corrected_text, translated_text, speakers(speaker_tag, display_name)")
      .eq("meeting_id", meeting_id)
      .order("created_at", { ascending: false })
      .limit(4);

    const historyContext = (recentTxs || [])
      .reverse()
      .map((tx: any) => ({
        speaker_tag: tx.speakers?.speaker_tag || "unknown",
        speaker_name: tx.speakers?.display_name || "Unknown",
        text: tx.corrected_text || tx.original_text,
        translation: tx.translated_text
      }));

    // 4. Prepare drafts context
    const draftsContext = drafts.map((d: any, idx: number) => ({
      index: idx + 1,
      speaker_tag: d.speakerTag,
      speaker_name: d.speakerName,
      text: d.text
    }));

    const targetLang = meeting.target_language;
    const sourceLang = meeting.source_language;
    const context = meeting.meeting_context;

    const systemPrompt = `
You are an expert dialogue editor and translator. Your job is to process a sequence of raw speech transcript segments from a live bilingual conversation (Japanese and Vietnamese/English), correct transcription errors, and translate each turn.

CONVERSATION HISTORY (Use for xưng hô/politeness consistency and pronouns context):
${JSON.stringify(historyContext)}

CONTEXT OF THE MEETING:
${context || "General business/technical discussion"}

GLOSSARY (Must apply if matching words are found):
${JSON.stringify(glossaryList || [])}

RAW DIALOGUE SEQUENCE:
${JSON.stringify(draftsContext)}

TASK & STRICT RULES:
1. STRICT SPEAKER GROUPING & NO DUPLICATES:
   - Group consecutive turns of the SAME speaker in the output array. Do NOT return consecutive turns with the same speaker_tag.
   - Clean up extreme stuttering or voice recognition word loops within a sentence (e.g., if a word like "ずっと" is repeated 5 times like "ずっとずっとずっとずっとずっと", clean it up to just "ずっと" or "ずっとずっと" to make the text clean and readable).
   - If a speaker has duplicate phrases or loops across their consecutive raw turns (e.g. Turn 1: "フランスに住んでいます", Turn 2: "住んでいます"), merge them into a single clean sentence without duplicate repetitions.

2. LISTENING RESPONSES (AIZUCHI / BACKCHANNELING):
   - In Japanese conversation, backchanneling words (like "なるほど", "うん", "はい", "そうですね", "ok", "oh") are spoken by the listener to show they are listening.
   - Check the context: if an aizuchi word (like "なるほど") is appended to the end of a speaker's turn, it almost always belongs to the OTHER speaker (the listener responding to the speaker's statement). Assign it to the correct listener's turn in the JSON.

3. BIOMETRIC-FIRST DIARIZATION & SPEAKER TAG PRESERVATION:
   - The raw speaker tags (speaker_0, speaker_1, speaker_2, etc.) were generated by the audio transcription system using biometric voice clustering. You should respect these voice distinctions to keep different speakers separate.

4. CORRECT SPEAKER CLASSIFICATION ERRORS:
   - You MUST correct and re-assign speaker tags when you are contextually or linguistically certain that the tag is incorrect.
   - For example, if a Japanese sentence is spoken by the Japanese speaker (e.g. Speaker 1) but raw diarization tagged it as Speaker B (e.g. speaker_0), you MUST change it to the correct speaker tag (e.g. speaker_1).
   - Use the conversation history and language clues (e.g., who is the host, who is the Japanese partner, who is speaking Japanese vs. Vietnamese/English) to decide the correct speaker tag for each turn.

5. SPLIT SINGLE SEGMENTS WITH MULTIPLE SPEAKERS:
   - If a single raw transcript segment contains text spoken by different people (e.g. a question followed immediately by a response, or a Japanese sentence followed immediately by a Vietnamese/English sentence, or two different Japanese speaker voices), you MUST split this single segment into two or more separate turns in the JSON array.
   - **Crucially: Assign distinct, correct speaker tags (e.g. speaker_0 to the host, speaker_1 to the Japanese speaker) to each split turn! Do NOT assign the same speaker tag to both parts of the split conversation!**

6. STRICT WORD PRESERVATION:
   - Preserve the exact spoken vocabulary. Do NOT rewrite, summarize, or try to "improve" the speaker's grammar/speech. Do not omit any actual thoughts. Keep Japanese politeness levels exactly as spoken.

7. TRANSLATION:
   - Translate each grouped dialogue turn into "${targetLang}" contextually and naturally.

OUTPUT FORMAT:
Return a valid JSON object ONLY. Do not write any markdown code fences, do not write explanations.
JSON format must be exactly:
{
  "cleaned_turns": [
    {
      "speaker_tag": "the correct speaker tag (e.g. speaker_0 or speaker_1)",
      "original_text": "cleaned and corrected text in the source language",
      "translated_text": "translated text into ${targetLang}"
    }
  ]
}
`;

    // 4. Setup Gemini Client & Call API
    const genAI = new GoogleGenerativeAI(geminiApiKey);
    const modelName = process.env.AI_FAST_MODEL || "gemini-3.1-flash-lite";
    const model = genAI.getGenerativeModel({ 
      model: modelName,
      generationConfig: { responseMimeType: "application/json" }
    });

    let result;
    try {
      result = await model.generateContent(systemPrompt);
    } catch (err) {
      console.warn(`Model ${modelName} failed, falling back to gemini-3.1-flash-lite:`, err);
      const fallbackModel = genAI.getGenerativeModel({ 
        model: "gemini-3.1-flash-lite",
        generationConfig: { responseMimeType: "application/json" }
      });
      result = await fallbackModel.generateContent(systemPrompt);
    }

    const responseText = result.response.text().trim();
    const aiResponse = JSON.parse(responseText);
    const cleanedTurns = aiResponse.cleaned_turns || [];

    // 5. Group consecutive turns of the same speaker inside the batch
    const groupedTurns: any[] = [];
    for (const turn of cleanedTurns) {
      const prev = groupedTurns[groupedTurns.length - 1];
      if (prev && prev.speaker_tag === turn.speaker_tag) {
        prev.original_text = (prev.original_text + "\n" + turn.original_text).trim();
        prev.translated_text = (prev.translated_text + "\n" + turn.translated_text).trim();
      } else {
        groupedTurns.push({ ...turn });
      }
    }

    // 6. Fetch the last transcript in database for potential merge
    const { data: lastTx } = await supabase
      .from("transcripts")
      .select(`
        id, original_text, corrected_text, translated_text, start_ms, end_ms, created_at,
        speakers ( id, speaker_tag, display_name )
      `)
      .eq("meeting_id", meeting_id)
      .order("start_ms", { ascending: false })
      .limit(1)
      .maybeSingle();

    const finalizedBlocks: any[] = [];
    let startIndex = 0;

    const startMsVal = drafts[0]?.startMs || Date.now();
    const endMsVal = drafts[drafts.length - 1]?.endMs || Date.now();
    const duration = endMsVal - startMsVal;
    const step = groupedTurns.length > 1 ? Math.round(duration / groupedTurns.length) : duration;

    // Check if we can merge the first turn into lastTx
    if (
      lastTx &&
      (lastTx as any).speakers?.speaker_tag === groupedTurns[0]?.speaker_tag &&
      (startMsVal - (lastTx as any).end_ms) < 60000 &&
      groupedTurns.length > 0
    ) {
      const firstTurn = groupedTurns[0];
      const mergedOriginal = ((lastTx as any).original_text + "\n" + firstTurn.original_text).trim();
      const mergedTranslated = ((lastTx as any).translated_text + "\n" + firstTurn.translated_text).trim();
      const turnEndMs = startMsVal + step;

      // Update lastTx in DB
      const { data: updatedTx } = await supabase
        .from("transcripts")
        .update({
          original_text: mergedOriginal,
          corrected_text: mergedOriginal,
          translated_text: mergedTranslated,
          end_ms: turnEndMs,
        })
        .eq("id", lastTx.id)
        .select()
        .single();

      if (updatedTx) {
        finalizedBlocks.push({
          id: lastTx.id,
          text: mergedOriginal,
          correctedText: mergedOriginal,
           translatedText: mergedTranslated,
          speakerTag: firstTurn.speaker_tag,
          speakerName: (lastTx as any).speakers?.display_name || (firstTurn.speaker_tag === "speaker_0" ? "Tôi" : firstTurn.speaker_tag.replace("speaker_", "Speaker ")),
          startMs: (lastTx as any).start_ms,
          endMs: turnEndMs,
          confidence: 1.0,
          status: "completed",
          createdAt: (lastTx as any).created_at || new Date().toISOString(),
        });
      }
      startIndex = 1; // Skip the first turn since we merged it
    }

    // Insert remaining turns
    for (let i = startIndex; i < groupedTurns.length; i++) {
      const turn = groupedTurns[i];
      const turnSpeakerTag = turn.speaker_tag || "speaker_0";
      
      // Resolve Speaker ID
      let speakerId = null;
      let resolvedSpeaker = null;
      
      const { data: speaker } = await supabase
        .from("speakers")
        .select("*")
        .eq("meeting_id", meeting_id)
        .eq("speaker_tag", turnSpeakerTag)
        .maybeSingle();

      if (speaker) {
        speakerId = speaker.id;
        resolvedSpeaker = speaker;
      } else {
        const { data: newSpeaker } = await supabase
          .from("speakers")
          .insert({
            meeting_id,
            speaker_tag: turnSpeakerTag,
            display_name: turnSpeakerTag === "speaker_0" ? "Tôi" : turnSpeakerTag.replace("speaker_", "Speaker "),
            color_hex: "#" + Math.floor(Math.random() * 16777215).toString(16).padStart(6, "0"),
          })
          .select().single();
        if (newSpeaker) {
          speakerId = newSpeaker.id;
          resolvedSpeaker = newSpeaker;
        }
      }

      const turnStartMs = startMsVal + step * i;
      const turnEndMs = startMsVal + step * (i + 1);

      // Insert new Transcript
      const { data: insertedTx } = await supabase
        .from("transcripts")
        .insert({
          meeting_id,
          speaker_id: speakerId,
          original_text: turn.original_text,
          corrected_text: turn.original_text,
          translated_text: turn.translated_text,
          translation_language: targetLang,
          translation_provider: "Gemini",
          start_ms: turnStartMs,
          end_ms: turnEndMs,
          confidence: 1.0,
        })
        .select()
        .single();

      if (insertedTx) {
        finalizedBlocks.push({
          id: insertedTx.id,
          text: turn.original_text,
          correctedText: turn.original_text,
          translatedText: turn.translated_text,
          speakerTag: turnSpeakerTag,
          speakerName: resolvedSpeaker?.display_name || (turnSpeakerTag === "speaker_0" ? "Tôi" : turnSpeakerTag.replace("speaker_", "Speaker ")),
          startMs: turnStartMs,
          endMs: turnEndMs,
          confidence: 1.0,
          status: "completed",
          createdAt: insertedTx.created_at || new Date().toISOString(),
        });
      }
    }

    return NextResponse.json({
      blocks: finalizedBlocks
    });
  } catch (error) {
    console.error("Process transcript batch error:", error);
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
